### PR TITLE
Page/about

### LINKED ISSUE #7: page/about
write up information about what we do 
and how to contact us !

maybe make a visual

### LINKED ISSUE #18: page/contact
add simple / template contact us

### PR DESCRIPTION
**Pull request by Pandaphobic**
Mac and I worked on the new about page! Nice little collab looking pretty slick :sunglasses:

### CODE REVIEW

**Review by MacMenard — APPROVED** [review]
looks good, like the opening line

**Review by MillieGrey — APPROVED** [review]
Looks good!

**Review by princerori — APPROVED** [review]
Nice work!

**Comment by MacMenard** [comment]
merging PR

**Pull request closed without merging**
