### PR TITLE
Url Fix 

### LINKED ISSUE #52: when on midheavy.tech/anything you cant refresh the page

### PR DESCRIPTION
**Pull request by Pandaphobic**
implemented fix based on the below. Now URLs should always link back to home, avoiding 404 errors for mh.tech/urls

https://ridbay.medium.com/react-routing-and-netlify-redirects-fd1f00eeee95

### CODE REVIEW

**Review by MacMenard — APPROVED** [review]
looks good

**Review by MacMenard — COMMENTED** [review]
looks good

**Review by MillieGrey — APPROVED** [review]
kk

**Review by princerori — APPROVED** [review]
looks great

**Pull request merged**
