### PR TITLE
Added a delay to fix glitchy initial animation

### LINKED ISSUE #5: Animation hiccoughs on page load
the animation seems to stutter on page load, could be solved with a small delay before running the animation

### PR DESCRIPTION
**Pull request by MillieGrey**
Added a delay to fix glitchy initial animation, also made the MidHeavy.Tech fade in during the delay because it looked naked on its own.
sped up the time factor a little cause it doesn't fall apart as much at faster values anymore.

https://user-images.githubusercontent.com/83617863/126950084-9b236977-32e8-4d0f-b81c-8aedc145e2a6.mp4

### CODE REVIEW

**Review by Pandaphobic — APPROVED** [review]
Looks good to me! I like the implementation, 2 birds with one stone!

**Review by princerori — APPROVED** [review]
good stuff

**Review by MacMenard — APPROVED** [review]
not much but itd honest work!

**Comment by MacMenard** [comment]
> not much but itd honest work!

> not much but its honest work!

**Comment by MillieGrey** [comment]
> not much but itd honest work!

"itd"

**Pull request merged**
