### PR TITLE
Page/Contact

### PR DESCRIPTION
**Pull request by MacMenard**
Added Contact page, HTML, CSS

Please review and tell me what you think :)

### CODE REVIEW

**Review by Pandaphobic — CHANGES_REQUESTED** [review]
The contact section seems to draw on the left side - I think it makes more sense to center it
Screen Shot 2021-08-13 at 11 40 04 AM

**Comment by MillieGrey** [comment]
just realized this is also the branch for the contact page aswell, just fleshed out the about section pretty sure rori and i didn't step on anything we shouldn't have but if we have we can roll back the most recent commit before we merge.

**Comment by MacMenard** [comment]
@MillieGrey before we merge this big PR, we'll all review it as a group on Mid-Monday! 
Any issues or bugs will be fixed! if not, we can great some issues for the team to work on :)

**Comment by Pandaphobic** [comment]
This was merged manually for compatibility reasons
closed PR

**Pull request closed without merging**
