### PR TITLE
Prettierrc

### LINKED ISSUE #87: .prettierrc.js file
Prettier config specified in the project

### PR DESCRIPTION
**Pull request by Pandaphobic**
Added prettier with my defaults

### CODE REVIEW

**Review by princerori — CHANGES_REQUESTED** [review]
I'm willing to be convinced, but I don't agree with any of those setting 😂
Can you explain why?

**Comment by Pandaphobic** [comment]
For the most part, I've started using these to make my code have less boilerplate / dead code. Here are some explanations in no particular order
- Semicolons are not necessary and look gross

- 4 spaces causes alot more spread out code and leads to word wrapping (which I feel strongly about) whereas 2 keeps things tighter together

- trailing commas look wrong. in every other context, a comma means something else is coming next. Consider the following object declarations with and without trailing comma
const obj = {
  item1: "item text",
  item2: "item 2 text",
}

const obj = {
  item1: "item text",
  item2: "item 2 text"
}

- single quote is one key push, double is 2, they are the same to the compiler so why not use the one thats less keystrokes. 


Can you tell me what specifically you oppose on these?

**Review by princerori — APPROVED** [review]
honestly hearing your explanations has reduced my opposition almost entirely. I'm happy to comply knowing that it matters to you.
also especially since i now understand that a prettier file does not require me to change my prettier settings in other projects.

**Review by MillieGrey — APPROVED** [review]
yes pls

**Pull request merged**
