### PR TITLE
Millie

### LINKED ISSUE #1: Readme is bad!
I think the readme needs work!

### PR DESCRIPTION
**Pull request by MillieGrey**
Made a better ReadMe

### CODE REVIEW

**Comment by Pandaphobic** [comment]
looks like theres a lil bug on line one ;)

**Review by Pandaphobic — APPROVED** [review]
Looks good!

**Review by princerori — APPROVED** [review]
lookin good sweetie

**Review by MacMenard — APPROVED** [review]
not bad for a rookie ;)

**Pull request merged**
